name: Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHA
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install modules
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Unit tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
